[build]
command = """
pnpm install && \
pnpm run build --base $DEPLOY_PRIME_URL/ --mirror netlify && \
cp -r ./assets/ ./dist
"""
# $DEPLOY_PRIME_URL is set by netlify: https://docs.netlify.com/build/configure-builds/environment-variables/#deploy-urls-and-metadata
publish = "dist"

[build.processing.html]
# Toggling theme (assets/main.js) requires the exact URL structure.
pretty_urls = false
